apps/adopcion/urls.py
from django.conf.urls import url
from apps.adopcion.views import PersonaList, PersonaCreate, PersonaDelete, PersonaUpdate, persona_create, persona_list, persona_delete, persona_update, adopcion_update,adopcion_delete,adopcion_create,adopcion_list, solicitud_create, solicitud_list, solicitud_update, solicitud_delete, persona_list, persona_create, persona_delete, persona_update, AdopcionUpdate,AdopcionDelete,AdopcionCreate,AdopcionList, SolicitudCreate, SolicitudList, SolicitudUpdate, SolicitudDelete
urlpatterns = [
    #clases
    url(r'^solicitud/$', SolicitudList.as_view(), name='solicitud_listar'),
    url(r'^solicitud/crear/$', SolicitudCreate.as_view(), name="solicitud_crear"),
    url(r'^solicitud/editar/(?P<pk>\d+)/$', SolicitudUpdate.as_view(), name='solicitud_editar'),
    url(r'^solicitud/eliminar/(?P<pk>\d+)/$', SolicitudDelete.as_view(), name='solicitud_eliminar'),
    
    url(r'^$', AdopcionList.as_view(), name='adopcion_listar'),
    url(r'^crear/$', AdopcionCreate.as_view(), name="adopcion_crear"),
    url(r'^editar/(?P<pk>\d+)/$', AdopcionUpdate.as_view(), name='adopcion_editar'),
    url(r'^eliminar/(?P<pk>\d+)/$', AdopcionDelete.as_view(), name='adopcion_eliminar'),

    url(r'^persona/$', PersonaList.as_view(), name='persona_listar'),
    url(r'^persona/crear/$', PersonaCreate.as_view(), name="persona_crear"),
    url(r'^persona/editar/(?P<pk>\d+)/$', PersonaUpdate.as_view(), name='persona_editar'),
    url(r'^persona/eliminar/(?P<pk>\d+)/$', PersonaDelete.as_view(), name='persona_eliminar'),

    #funciones

    url(r'^solicitud/f/$', solicitud_list, name='f_solicitud_listar'),
    url(r'^solicitud/f/crear/$', solicitud_create, name="f_solicitud_crear"),
    url(r'^solicitud/f/editar/(?P<pk>\d+)/$', solicitud_update, name='f_solicitud_editar'),
    url(r'^solicitud/f/eliminar/(?P<pk>\d+)/$', solicitud_delete, name='f_solicitud_eliminar'),
    
    url(r'^f/$', adopcion_list, name='f_adopcion_listar'),
    url(r'^f/crear/$', adopcion_create, name="f_adopcion_crear"),
    url(r'^f/editar/(?P<pk>\d+)/$', adopcion_update, name='f_adopcion_editar'),
    url(r'^f/eliminar/(?P<pk>\d+)/$', adopcion_delete, name='f_adopcion_eliminar'),

    url(r'^persona/f/$', persona_list, name='f_persona_listar'),
    url(r'^persona/f/crear/$', persona_create, name="f_persona_crear"),
    url(r'^persona/f/editar/(?P<pk>\d+)/$', persona_update, name='f_persona_editar'),
    url(r'^persona/f/eliminar/(?P<pk>\d+)/$', persona_delete, name='f_persona_eliminar'),

]

apps/mascota/urls.py
from django.conf.urls import url
from apps.mascota.views import index, mascota_create, mascota_list, mascota_edit, mascota_delete, MascotaList, MascotaCreate, MascotaUpdate, MascotaDelete
urlpatterns = [
    #version de clases
    url(r'^$', index, name="index"),
    url(r'^mascota/nuevo/$', MascotaCreate.as_view(), name="mascota_crear"),
    url(r'^mascota/listar/$', MascotaList.as_view(), name='mascota_listar'),
    url(r'^mascota/editar/(?P<pk>\d+)/$', MascotaUpdate.as_view(), name='mascota_editar'),
    url(r'^mascota/eliminar/(?P<pk>\d+)/$', MascotaDelete.as_view(), name='mascota_eliminar'),
    #version de funciones
    url(r'^mascota/f_nuevo/$', mascota_create, name="f_mascota_crear"),
    url(r'^mascota/f_listar/$', mascota_list, name='f_mascota_listar'),
    url(r'^mascota/f_editar/(?P<pk>\d+)/$', mascota_edit, name='f_mascota_editar'),
    url(r'^mascota/f_eliminar/(?P<pk>\d+)/$', mascota_delete, name='f_mascota_eliminar'),
]

refugio/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include ( 'apps.mascota.urls',namespace="mascota")),
    url(r'^adopciones/', include ( 'apps.adopcion.urls',namespace="adopcion")),
    url(r'^usuario/', include ( 'apps.usuario.urls',namespace="usuario")),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)



#url(r'^$', login, {"template_name":"index.html"}, name="login"),
    #url(r'^accounts/login/', login, {'template_name':'index.html'}, name='login'),
    #url(r'^logout/', logout_then_login, name='logout'),
    # url(r'^reset/password_reset', password_reset, 
    #     {'template_name':'registration/password_reset_form.html',
    #     'email_template_name': 'registration/password_reset_email.html'}, 
    #     name='password_reset'), 
    # url(r'^password_reset_done', password_reset_done, 
    #     {'template_name': 'registration/password_reset_done.html'}, 
    #     name='password_reset_done'),
    # url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>.+)/$', password_reset_confirm, 
    #     {'template_name': 'registration/password_reset_confirm.html'},
    #     name='password_reset_confirm'
    #     ),
    # url(r'^reset/done', password_reset_complete, {'template_name': 'registration/password_reset_complete.html'},
    #     name='password_reset_complete'),

templates/base/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% block extrasstatic %}
    {% endblock %}
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <title>{% block title %} Document {% endblock %}</title>
    <style>
        .links p a{
            text-decoration: none;
            color: gray;
            transition: 0.5s;
        }
        .links p a:hover{
            font-size: 19px;
            color: white;
            transition: 0.5s;
        }
    </style>
</head>
<body>
    {% block header %}
    <div class="bg-dark">
        <div class="container d-flex justify-content-between py-3">
        <h4 class="text-white">Refugio</h4>
        <div class="links d-flex justify-content-center align-content-center align-items-center">
            <p class="px-2 m-0">
                <a href="{% url 'mascota:mascota_listar' %}">Mascotas</a>
                <a href="{% url 'mascota:f_mascota_listar' %}">VF Mascotas</a>
            </p>
            <p class="px-2 m-0">
                <a href="{% url 'adopcion:solicitud_listar' %}">Solicitudes</a>
                <a href="{% url 'adopcion:f_solicitud_listar' %}">VF Solicitudes</a>
            </p>
            <p class="px-2 m-0">
                <a href="{% url 'adopcion:adopcion_listar' %}">Adopciones</a>
                <a href="{% url 'adopcion:f_adopcion_listar' %}">VF Adopciones</a>
            </p>
            <p class="px-2 m-0">
                <a href="{% url 'adopcion:persona_listar' %}">Personas</a>
                <a href="{% url 'adopcion:f_persona_listar' %}">VF Personas</a>
            </p>
        </div>
        </div>
    </div>
    {% endblock %}

    {% if messages %}
        {% for message in messages %}
            <div class="alert-{{ message.level_tag }} p-3 text-center" role="alert">
                {{ message }}
            </div>
        {% endfor %}
    {% endif %}

    <div class="text-darktext-center py-4 " style="min-height: 100vh;">
        <div class="container">
            {% block content %}
                <h2>contenerdor</h2>
            {% endblock %}
        </div>
    </div>

    {% block footer %}
<footer class="bg-dark text-white text-center py-4 d-flex">
    <div class="container">
        <div class="row">
            green <div class="col-md-4">
                <h5>Sobre Nosotros</h5>
                <p>Somos una refugio.</p>
            </div>
            <div class="col-md-4">
                <h5>Derechos reservados</h5>
                <p><i class="fas fa-envelope"></i> wisp@gmail.com</p>
            </div>
        </div>
    </div>
</footer>
{% endblock %}
    <script src="{% static 'js/bootstrap.min.js'%}"></script>
    {% block scripts %}
    {% endblock %}
</body>
</html>