apps/mascota/urls.py
from django.conf.urls import url
from apps.mascota.views import index, mascota_create, mascota_list, mascota_edit, mascota_delete, MascotaList, MascotaCreate, MascotaUpdate, MascotaDelete
urlpatterns = [
    #version de clases
    url(r'^$', index, name="index"),
    url(r'^mascota/nuevo/$', MascotaCreate.as_view(), name="mascota_crear"),
    url(r'^mascota/listar/$', MascotaList.as_view(), name='mascota_listar'),
    url(r'^mascota/editar/(?P<pk>\d+)/$', MascotaUpdate.as_view(), name='mascota_editar'),
    url(r'^mascota/eliminar/(?P<pk>\d+)/$', MascotaDelete.as_view(), name='mascota_eliminar'),
    #version de funciones
    url(r'^mascota/f_nuevo/$', mascota_create, name="f_mascota_crear"),
    url(r'^mascota/f_listar/$', mascota_list, name='f_mascota_listar'),
    url(r'^mascota/f_editar/(?P<pk>\d+)/$', mascota_edit, name='f_mascota_editar'),
    url(r'^mascota/f_eliminar/(?P<pk>\d+)/$', mascota_delete, name='f_mascota_eliminar'),
]

refugio/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include ( 'apps.mascota.urls',namespace="mascota")),
    url(r'^adopciones/', include ( 'apps.adopcion.urls',namespace="adopcion")),
    url(r'^usuario/', include ( 'apps.usuario.urls',namespace="usuario")),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)



#url(r'^$', login, {"template_name":"index.html"}, name="login"),
    #url(r'^accounts/login/', login, {'template_name':'index.html'}, name='login'),
    #url(r'^logout/', logout_then_login, name='logout'),
    # url(r'^reset/password_reset', password_reset, 
    #     {'template_name':'registration/password_reset_form.html',
    #     'email_template_name': 'registration/password_reset_email.html'}, 
    #     name='password_reset'), 
    # url(r'^password_reset_done', password_reset_done, 
    #     {'template_name': 'registration/password_reset_done.html'}, 
    #     name='password_reset_done'),
    # url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>.+)/$', password_reset_confirm, 
    #     {'template_name': 'registration/password_reset_confirm.html'},
    #     name='password_reset_confirm'
    #     ),
    # url(r'^reset/done', password_reset_complete, {'template_name': 'registration/password_reset_complete.html'},
    #     name='password_reset_complete'),

apps/adopcion/models.py
from django.db import models

# Create your models here.
#from apps.adopcion.models import Persona
 

# class Vacuna(models.Model):
#     mombre = models.CharField(max_length=50)

class Persona(models.Model):
    nombre = models.CharField(max_length=50)
    apellidos = models.CharField(max_length=70)
    edad = models.IntegerField()
    telefono= models.CharField( null=True, max_length=12)
    email = models.EmailField()
    domicilio = models.TextField()

    def __str__(self):
        return "{} {}".format(self.nombre, self.apellidos)

class Solicitud(models.Model):
    persona = models.ForeignKey(Persona, null=True, blank=True)
    numero_mascotas = models.IntegerField()
    razones = models.TextField() 

apps/mascota/models.py
from django.db import models
from apps.adopcion.models import Persona

class Vacuna(models.Model):
    nombre = models.CharField(max_length=50)
    def __str__(self):
        return self.nombre

# Create your models here.
class Mascota(models.Model):
    nombre = models.CharField(max_length=50)
    sexo = models.CharField(max_length=10)
    edad_aproximada = models.IntegerField()
    fecha_rescate = models.DateField()
    #si se elimina la persona igual se eliminara la mascota
    #esto como que no me da mucho sentido :v
    persona = models.ForeignKey(Persona, null=True, blank=True, on_delete=models.CASCADE)
    vacuna = models.ManyToManyField(Vacuna, blank=True)
    foto = models.ImageField(upload_to="mascotas/", blank=True, null=True)

    def __str__(self):
        return self.nombre

apps/mascota/forms.py
from django import forms
from apps.mascota.models import Mascota

class MascotaForm(forms.ModelForm):
    class Meta:
        model = Mascota
        fields = [
            "nombre",
            "sexo",
            "edad_aproximada",
            "fecha_rescate",
            "persona",
            "vacuna",
            "foto"
        ]
        labels = {
            "nombre": "Nombre",
            "sexo": "Sexo",
            "edad_aproximada": "Edad Aproximada",
            "fecha_rescate": "Fecha de Rescate",
            "persona": "Persona",
            "vacuna":"Vacunas",
            "foto":"Foto"
        }
        widgets = {
            "nombre": forms.TextInput(attrs={"class":"form-control"}),
            "sexo": forms.TextInput(attrs={"class":"form-control"}),
            "edad_aproximada": forms.TextInput(attrs={"class":"form-control"}),
            "fecha_rescate": forms.TextInput(attrs={"class": "form-control", "type": "date",},), 
            "persona": forms.Select(attrs={"class":"form-control"}),
            "vacuna": forms.CheckboxSelectMultiple(attrs={"class":"form-check-input"}),
        }

apps/mascota/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse
from django.views.generic import ListView, CreateView, UpdateView, DeleteView
from django.core.urlresolvers import reverse_lazy
from apps.mascota.forms import MascotaForm
from apps.mascota.models import Mascota
from django.contrib import messages
from django.contrib.messages.views import SuccessMessageMixin
# Create your views here.

def index (request):
    return render(request, "mascota/index.html")

def mascota_create(request):
    if request.method == "POST":
        form = MascotaForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Mascota exitosamente creada')
            return redirect("mascota:f_mascota_listar")
        else:
            messages.info(request, 'Existen campos faltantes')
    else:
        form = MascotaForm()
    return render(request, "mascota/mascota_form.html", {"form": form})

def mascota_list(request):
    mascota = Mascota.objects.all().order_by("-id")
    contexto = {"mascotas": mascota}
    return render(request, "mascota/mascota_list.html", contexto)

class MascotaList(ListView):
    model = Mascota
    template_name = "mascota:mascota_list.html"
    context_object_name = "mascotas"


def mascota_edit(request, pk):
    mascota = get_object_or_404(Mascota, id=pk)
    if request.method == "GET":
        form = MascotaForm(instance=mascota)
    else:
        form = MascotaForm(request.POST, instance=mascota)
        if form.is_valid():
            form.save()
            messages.success(request, 'Mascota actualizada exitosamente')
            return redirect("mascota:f_mascota_listar")
        else:
            messages.info(request, 'Existen campos faltantes o incorrectos')
    return render(request, "mascota/mascota_form.html", {"form": form})

def mascota_delete(request, pk):
    mascota = get_object_or_404(Mascota, id=pk)
    if request.method == "POST":
        mascota.delete()
        messages.success(request, 'Mascota eliminada exitosamente')
        return redirect("mascota:f_mascota_listar")
    return render(request, "mascota/mascota_delete.html", {"object": mascota})

class MascotaCreate(SuccessMessageMixin, CreateView):
    model = Mascota
    form_class = MascotaForm
    template_name = "mascota/mascota_form.html"
    success_url = reverse_lazy("mascota:mascota_listar")
    
    def form_invalid(self, form):
        messages.info(self.request, "Existen campos faltantes o incorrectos")
        return super().form_invalid(form)

    def form_valid(self, form):
        messages.success(self.request, "Mascota creada exitosamente")
        return super().form_valid(form)

class MascotaUpdate(SuccessMessageMixin, UpdateView):
    # - be for defect object 
    #  model = Mascota
    form_class = MascotaForm
    template_name = "mascota/mascota_form.html"
    # success_url = reverse_lazy("mascota:mascota_listar")

    # personaisa el direccionamiento
    def get_success_url(self):
        return reverse_lazy("mascota:mascota_listar")

    # personalizate form the request in the path
    def get_object(self):
        _id = self.kwargs.get("pk")
        return get_object_or_404(Mascota, id=_id)

    def form_invalid(self, form):
        messages.info(self.request, "Existen campos faltantes o incorrectos")
        return super().form_invalid(form)

    def form_valid(self, form):
        messages.success(self.request, "Mascota actualizada exitosamente")
        return super().form_valid(form)

class MascotaDelete(DeleteView):
    model = Mascota
    template_name = "mascota/mascota_delete.html"
    success_url = reverse_lazy("mascota:mascota_listar")
    
    def delete(self, request, *args, **kwargs):
        messages.success(self.request, "Mascota eliminada exitosamente")
        return super().delete(request, *args, **kwargs)

templates/mascota/index.html
{% extends "base/base.html" %}


{% block content %}
<h1>Bienvenido</h1>
{% endblock %}

templates/mascota/mascota_delete.html
{% extends "base/base.html" %}

{% block title %}
    Eliminar Mascota
{% endblock %}

{% block content %}
<form method="post">
    {% csrf_token %}
    <h2>Desea eliminar el registro de {{ object.nombre }}</h2>
    <button class="btn btn-danger" type="submit">
    Si eliminar
    </button>
    <a class="btn btn-default" href="{% url 'mascota:mascota_listar' %}">
        cancelar
    </a>
</form>
{% endblock %}

templates/mascota/mascota_form.html
{% extends "base/base.html" %}

{% block title %} 
creacion de una mascota
{% endblock %}


{% block content %}
<form method="post" id="solicitud-form" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="row">
        <!-- Formulario Persona (Solicitante) -->
        <div class="col-md-6"> 
            <div class="mb-3">
                <label for="id_nombre" class="form-label">Nombre</label>
                {{ form.nombre }}
                {% if form.nombre.errors %}
                    <div class="invalid-feedback d-block">
                        {% for error in form.nombre.errors %}
                            <p>{{ error }}</p>
                        {% endfor %}
                    </div>
                {% endif %}
            </div>
        </div>
        <div class="col-md-6">
            <div class="mb-3">
                <label for="id_apellidos" class="form-label">Sexo</label>
                {{ form.sexo }}
                {% if form.sexo.errors %}
                    <div class="invalid-feedback d-block">
                        {% for error in form.sexo.errors %}
                            <p>{{ error }}</p>
                        {% endfor %}
                    </div>
                {% endif %}
            </div>
        </div>
        <div class="col-md-6">
            <div class="mb-3">
                <label for="id_edad" class="form-label">Edad Aproximada</label>
                {{ form.edad_aproximada }}
                {% if form.edad_aproximada.errors %}
                    <div class="invalid-feedback d-block">
                        {% for error in form.edad_aproximada.errors %}
                            <p>{{ error }}</p>
                        {% endfor %}
                    </div>
                {% endif %}
            </div>
        </div>
        <div class="col-md-6">
            <div class="mb-3">
                <label for="id_telefono" class="form-label">Fecha de rescate</label>
                {{ form.fecha_rescate }}
                {% if form.fecha_rescate.errors %}
                    <div class="invalid-feedback d-block">
                        {% for error in form.fecha_rescate.errors %}
                            <p>{{ error }}</p>
                        {% endfor %}
                    </div>
                {% endif %}
            </div>
        </div>
        <div class="col-md-12">
            <div class="mb-3">
                <label for="id_email" class="form-label">Dueño</label>
                {{ form.persona }}
                {% if form.persona.errors %}
                    <div class="invalid-feedback d-block">
                        {% for error in form.persona.errors %}
                            <p>{{ error }}</p>
                        {% endfor %}
                    </div>
                {% endif %}
            </div>
        </div>

        <div class="col-md-12">
            <div class="d-flex flex-column ">
                    <label class="">Vacunas</label>
                        {{form.vacuna}}
                    {% if form.vacuna.errors %}
                    <div class="invalid-feedback d-block">
                        {% for error in form.vacuna.errors %}
                            <p>{{ error }}</p>
                        {% endfor %}
                    </div>
                {% endif %}
            </div>
        </div>
        <div class="col-md-12">
            <div class="mb-3">
                <label class="form-label">Foto</label>
                
                {{ form.foto }}

                {% if form.foto.errors %}
                    <div class="invalid-feedback d-block">
                        {% for error in form.foto.errors %}
                            <p>{{ error }}</p>
                        {% endfor %}
                    </div>
                {% endif %}
            </div>
        </div>
    </div>

    <button class="btn btn-success" type="submit">Enviar</button>
</form>
</form>
{% endblock %}

templates/mascota/mascota_list.html
{% extends "base/base.html" %}

{% block title %}
    Enlistar Mascotas
{% endblock %}

{% block content %}
<div class="d-flex justify-content-between align-items-center">
    <h1>Lista de Mascotas</h1>
    <a class="btn btn-success px-3" href="{% url 'mascota:mascota_crear' %}">
        + crear
    </a>
</div>

{% if mascotas %}
<div class="row">
    {% for mascota in mascotas %}
    <div class="col-md-4 mb-4">
        <div class="card">
            <img src="{% if mascota.foto %}{{ mascota.foto.url }}{% else %}https://www.tripleq.com/uploads/medium/empty-img.png{% endif %}" class="card-img-top" alt="{{ mascota.nombre }}" style="height: 300px; object-fit: cover;">
            <div class="card-body">
                <h5 class="card-title">{{ mascota.nombre }}</h5>
                <p class="card-text">
                    <strong>Sexo:</strong> {{ mascota.sexo }}<br>
                    <strong>Edad Aproximada:</strong> {{ mascota.edad_aproximada }}<br>
                    <strong>Fecha de Rescate:</strong> {{ mascota.fecha_rescate }}
                </p>
                <a href="{% if request.path == '/mascota/f_listar/' %}{% url 'mascota:f_mascota_editar' mascota.id %}{% else %}{% url 'mascota:mascota_editar' mascota.id %}{% endif %}" class="btn btn-warning">Editar</a>
                <a href="{% if request.path == '/mascota/f_listar/' %}{% url 'mascota:f_mascota_eliminar' mascota.id %}{% else %}{% url 'mascota:mascota_eliminar' mascota.id %}{% endif %}" class="btn btn-danger">Eliminar</a>
            </div>
        </div>
    </div>
    {% endfor %}
</div>
{% else %}
<h5>No hay Registros de mascotas</h5>
{% endif %}

{% endblock %}